// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _CreateObraEp } from '../src/api/createObra';
import type { default as _DashboardStatsEp } from '../src/api/dashboardStats';
import type { default as _DeleteObraEp } from '../src/api/deleteObra';
import type { default as _DeleteTodayEp } from '../src/api/deleteToday';
import type { default as _ExportCsvEp } from '../src/api/exportCsv';
import type { default as _ImportCsvEp } from '../src/api/importCsv';
import type { default as _ListAplicacoesEp } from '../src/api/listAplicacoes';
import type { default as _ListCidadesEp } from '../src/api/listCidades';
import type { default as _ListDuplicatasEp } from '../src/api/listDuplicatas';
import type { default as _ListObrasEp } from '../src/api/listObras';
import type { default as _UpdateObraEp } from '../src/api/updateObra';

type _CreateObraCfg = typeof _CreateObraEp;
export type CreateObraInputType = NonNullable<_CreateObraCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateObraCfg['execute']>[0]['input'];
export type CreateObraOutputType = Awaited<ReturnType<_CreateObraCfg['execute']>>;
export const createObra = createCaller<CreateObraInputType, CreateObraOutputType>('createObra');

type _DashboardStatsCfg = typeof _DashboardStatsEp;
export type DashboardStatsInputType = NonNullable<_DashboardStatsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DashboardStatsCfg['execute']>[0]['input'];
export type DashboardStatsOutputType = Awaited<ReturnType<_DashboardStatsCfg['execute']>>;
export const dashboardStats = createCaller<DashboardStatsInputType, DashboardStatsOutputType>('dashboardStats');

type _DeleteObraCfg = typeof _DeleteObraEp;
export type DeleteObraInputType = NonNullable<_DeleteObraCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteObraCfg['execute']>[0]['input'];
export type DeleteObraOutputType = Awaited<ReturnType<_DeleteObraCfg['execute']>>;
export const deleteObra = createCaller<DeleteObraInputType, DeleteObraOutputType>('deleteObra');

type _DeleteTodayCfg = typeof _DeleteTodayEp;
export type DeleteTodayInputType = NonNullable<_DeleteTodayCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteTodayCfg['execute']>[0]['input'];
export type DeleteTodayOutputType = Awaited<ReturnType<_DeleteTodayCfg['execute']>>;
export const deleteToday = createCaller<DeleteTodayInputType, DeleteTodayOutputType>('deleteToday');

type _ExportCsvCfg = typeof _ExportCsvEp;
export type ExportCsvInputType = NonNullable<_ExportCsvCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportCsvCfg['execute']>[0]['input'];
export type ExportCsvOutputType = Awaited<ReturnType<_ExportCsvCfg['execute']>>;
export const exportCsv = createCaller<ExportCsvInputType, ExportCsvOutputType>('exportCsv');

type _ImportCsvCfg = typeof _ImportCsvEp;
export type ImportCsvInputType = NonNullable<_ImportCsvCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ImportCsvCfg['execute']>[0]['input'];
export type ImportCsvOutputType = Awaited<ReturnType<_ImportCsvCfg['execute']>>;
export const importCsv = createCaller<ImportCsvInputType, ImportCsvOutputType>('importCsv');

type _ListAplicacoesCfg = typeof _ListAplicacoesEp;
export type ListAplicacoesInputType = NonNullable<_ListAplicacoesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListAplicacoesCfg['execute']>[0]['input'];
export type ListAplicacoesOutputType = Awaited<ReturnType<_ListAplicacoesCfg['execute']>>;
export const listAplicacoes = createCaller<ListAplicacoesInputType, ListAplicacoesOutputType>('listAplicacoes');

type _ListCidadesCfg = typeof _ListCidadesEp;
export type ListCidadesInputType = NonNullable<_ListCidadesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListCidadesCfg['execute']>[0]['input'];
export type ListCidadesOutputType = Awaited<ReturnType<_ListCidadesCfg['execute']>>;
export const listCidades = createCaller<ListCidadesInputType, ListCidadesOutputType>('listCidades');

type _ListDuplicatasCfg = typeof _ListDuplicatasEp;
export type ListDuplicatasInputType = NonNullable<_ListDuplicatasCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListDuplicatasCfg['execute']>[0]['input'];
export type ListDuplicatasOutputType = Awaited<ReturnType<_ListDuplicatasCfg['execute']>>;
export const listDuplicatas = createCaller<ListDuplicatasInputType, ListDuplicatasOutputType>('listDuplicatas');

type _ListObrasCfg = typeof _ListObrasEp;
export type ListObrasInputType = NonNullable<_ListObrasCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListObrasCfg['execute']>[0]['input'];
export type ListObrasOutputType = Awaited<ReturnType<_ListObrasCfg['execute']>>;
export const listObras = createCaller<ListObrasInputType, ListObrasOutputType>('listObras');

type _UpdateObraCfg = typeof _UpdateObraEp;
export type UpdateObraInputType = NonNullable<_UpdateObraCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateObraCfg['execute']>[0]['input'];
export type UpdateObraOutputType = Awaited<ReturnType<_UpdateObraCfg['execute']>>;
export const updateObra = createCaller<UpdateObraInputType, UpdateObraOutputType>('updateObra');


export const api = {
  createObra,
  dashboardStats,
  deleteObra,
  deleteToday,
  exportCsv,
  importCsv,
  listAplicacoes,
  listCidades,
  listDuplicatas,
  listObras,
  updateObra,
};
